[build]
  command = "npm run build"  # Replace with your build command if applicable
  functions = "functions"    # Path to Netlify functions folder if used
  publish = "views"          # Change this to the directory where your built frontend files reside

[dev]
  port = 3000                # The port number for the local development server

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
